[Project]
Name=modbusua
Log.flags="Error|Warning|Info|TraceDetails"
Log.output="file console"
Log.default.format="[%time] %src. %text"
Log.default.timeformat="%Y-%M-%D %h:%m:%s.%f"
Log.file.format="%time;%cat;%src;%text"
Log.file.timeformat="%h:%m:%s.%f"
Log.file.path="log.csv"
Log.file.maxcount=10
Log.file.maxsize=1000000

[OPCUA]
Port=4840
UncertainAs=Good#Bad#Good#Uncertain
